[package]
name = "winevt-core"
version = "0.2.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Core types and lookup tables for Windows Event Log forensic analysis"

[dependencies]
crc32fast = "1"
serde = { workspace = true }
forensicnomicon = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]

[lints]
workspace = true
